#Numpy array and operations

In [11]:
import numpy as np

In [12]:
arr =  np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing \n", arr[2:7])
print("With step", arr[1:8:2])
print("Negating indexing", arr[-3])

Basic slicing 
 [3 4 5 6 7]
With step [2 4 6 8]
Negating indexing 8


In [13]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("specific element", arr_2d[1,2])
print("entire row: \n", arr_2d[1])
print("Entir column: \n", arr_2d[:, 1])

specific element 6
entire row: 
 [4 5 6]
Entir column: 
 [2 5 8]


## sorting

In [14]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("sorted array: ", np.sort(unsorted)) # method me pass numpy array
arr_2d_unsorted = np.array([[3, 1],
                            [1, 2],
                            [2, 3]])

print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis = 0))
print("Sorted 2D array by row", np.sort(arr_2d_unsorted, axis = 1))

sorted array:  [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row [[1 3]
 [1 2]
 [2 3]]


## Filtering

In [15]:
numbers = np.array([[1,2,3,4,5,6,7,8,9,10]])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers", even_numbers)

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [17]:
mask = numbers > 5
print(" Numbers greater than 5:", numbers[mask])


 Numbers greater than 5: [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [18]:
indices = [0, 2, 4]
print("numbers[indiices]")

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

numbers[indiices]
(array([0, 0, 0, 0, 0]), array([5, 6, 7, 8, 9]))
NP where [ 6  7  8  9 10]
